bin/scion: fix regression when finding local ip
When using `scion sp` in HEAD versus older versions, this
error was happening:

```
host# scion sp 1-ff00:0:110 --refresh
Error: failed to determine local IP
    no entry found svc="CS A (0x0002)" services="map[]"
```